# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x03\x61\x32\x31\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t2@\n\x06Server\x12\x36\n\x16RegisterReplicaPrimary\x12\x0c.a21.Message\x1a\x0c.a21.Message\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=21
  _MESSAGE._serialized_end=47
  _SERVER._serialized_start=49
  _SERVER._serialized_end=113
# @@protoc_insertion_point(module_scope)
