# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eregistry.proto\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t2Y\n\x08Registry\x12%\n\rGetServerList\x12\x08.Message\x1a\x08.Message\"\x00\x12&\n\x0eRegisterServer\x12\x08.Message\x1a\x08.Message\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registry_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=18
  _MESSAGE._serialized_end=44
  _REGISTRY._serialized_start=46
  _REGISTRY._serialized_end=135
# @@protoc_insertion_point(module_scope)
